# Generated by Django 5.2.8 on 2025-12-03 04:52

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('hero', 'Hero Banner (Main)'), ('secondary', 'Secondary Banner'), ('footer', 'Footer Banner')], default='hero', max_length=20)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('heading', models.CharField(blank=True, help_text='Main heading text', max_length=300)),
                ('subheading', models.CharField(blank=True, help_text='Subheading text', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('button_text', models.CharField(blank=True, help_text='Call-to-action button text', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='Button URL', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tournament Banner',
                'verbose_name_plural': 'Tournament Banners',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TournamentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('about', 'About Tournament'), ('rules', 'Rules & Regulations'), ('schedule', 'Schedule'), ('highlights', 'Highlights'), ('sponsors', 'Sponsors'), ('gallery', 'Gallery'), ('custom', 'Custom Section')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML content supported')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tournament Content',
                'verbose_name_plural': 'Tournament Content',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g., 'Total Teams', 'Players Registered'", max_length=100)),
                ('value', models.CharField(help_text="e.g., '8', '120+'", max_length=50)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class, e.g., 'fas fa-trophy'", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tournament Statistic',
                'verbose_name_plural': 'Tournament Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('player', 'Player'), ('team_owner', 'Team Owner'), ('team_manager', 'Team Manager'), ('umpire', 'Umpire')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('player_type', models.CharField(blank=True, choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=10, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('course', models.CharField(blank=True, choices=[('btech', 'B.Tech'), ('polytechnic', 'Polytechnic'), ('iti', 'ITI')], max_length=20, null=True)),
                ('branch', models.CharField(blank=True, choices=[('cse', 'Computer Science Engineering'), ('me', 'Mechanical Engineering'), ('mining', 'Mining Engineering'), ('ee', 'Electrical Engineering'), ('ce', 'Civil Engineering')], max_length=20, null=True)),
                ('year_of_study', models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1, null=True)),
                ('suspended', models.BooleanField(default=False, help_text='Suspend user from system')),
                ('suspension_reason', models.TextField(blank=True, help_text='Reason for suspension')),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_users', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('platform',)},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('purse_remaining', models.IntegerField(default=10000)),
                ('total_purse', models.IntegerField(default=10000)),
                ('max_players', models.IntegerField(default=16)),
                ('iconic_players_count', models.IntegerField(default=0, help_text='Number of iconic players (reduces squad size)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_team', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('all_rounder', 'All Rounder'), ('wicket_keeper', 'Wicket Keeper')], max_length=20)),
                ('base_price', models.IntegerField(default=300)),
                ('current_bid', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sold', 'Sold'), ('unsold', 'Unsold')], default='pending', max_length=20)),
                ('batting_style', models.CharField(blank=True, max_length=50)),
                ('bowling_style', models.CharField(blank=True, max_length=50)),
                ('previous_team', models.CharField(blank=True, max_length=100)),
                ('is_iconic', models.BooleanField(default=False, help_text='Iconic players (faculty) - free assignment, reduce squad size')),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When iconic player was assigned', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='auction.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('paused', 'Paused'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid_call_count', models.IntegerField(default=0, help_text="Number of times auctioneer called 'Going once, twice...'")),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_auction', to='auction.player')),
                ('last_bid_team', models.ForeignKey(blank=True, help_text='Last team that bid on current player', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_bid_sessions', to='auction.team')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_amount', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='auction.auctionsession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.player')),
                ('winning_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.team')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaddleRaise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Bid amount when paddle was raised')),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False, help_text='Auctioneer acknowledged this paddle')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('auction_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paddle_raises', to='auction.auctionsession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.team')),
            ],
            options={
                'ordering': ['-raised_at'],
                'indexes': [models.Index(fields=['player', 'auction_session', '-raised_at'], name='auction_pad_player__486c39_idx'), models.Index(fields=['acknowledged', 'auction_session'], name='auction_pad_acknowl_d93d3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auctionsession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.team')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['player', 'auction_session', '-amount'], name='auction_bid_player__1ffaab_idx')],
            },
        ),
    ]
