# Generated by Django 5.2.8 on 2025-11-26 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='player',
            name='year',
        ),
        migrations.AddField(
            model_name='team',
            name='max_players',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('cse', 'Computer Science Engineering'), ('me', 'Mechanical Engineering'), ('mining', 'Mining Engineering'), ('ee', 'Electrical Engineering'), ('ce', 'Civil Engineering')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('btech', 'B.Tech'), ('polytechnic', 'Polytechnic'), ('iti', 'ITI')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='player_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, help_text='Format: 0242CS221003 (optional but must be unique)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_roll_number', message='Roll number must be in format: 0242CS221003', regex='^[0-9]{4}[A-Z]{2}[0-9]{6}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['player', 'auction_session', '-amount'], name='auction_bid_player__1ffaab_idx'),
        ),
    ]
