# Generated by Django 5.2.8 on 2025-11-30 10:31

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_user_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('hero', 'Hero Banner (Main)'), ('secondary', 'Secondary Banner'), ('footer', 'Footer Banner')], default='hero', max_length=20)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('heading', models.CharField(blank=True, help_text='Main heading text', max_length=300)),
                ('subheading', models.CharField(blank=True, help_text='Subheading text', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('button_text', models.CharField(blank=True, help_text='Call-to-action button text', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='Button URL', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tournament Banner',
                'verbose_name_plural': 'Tournament Banners',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TournamentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('about', 'About Tournament'), ('rules', 'Rules & Regulations'), ('schedule', 'Schedule'), ('highlights', 'Highlights'), ('sponsors', 'Sponsors'), ('gallery', 'Gallery'), ('custom', 'Custom Section')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML content supported')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tournament Content',
                'verbose_name_plural': 'Tournament Content',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g., 'Total Teams', 'Players Registered'", max_length=100)),
                ('value', models.CharField(help_text="e.g., '8', '120+'", max_length=50)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class, e.g., 'fas fa-trophy'", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tournament Statistic',
                'verbose_name_plural': 'Tournament Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='auctionsession',
            name='bid_call_count',
            field=models.IntegerField(default=0, help_text="Number of times auctioneer called 'Going once, twice...'"),
        ),
        migrations.AddField(
            model_name='auctionsession',
            name='last_bid_team',
            field=models.ForeignKey(blank=True, help_text='Last team that bid on current player', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_bid_sessions', to='auction.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended',
            field=models.BooleanField(default=False, help_text='Suspend user from system'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('team_owner', 'Team Owner'), ('team_manager', 'Team Manager'), ('umpire', 'Umpire'), ('auctioneer', 'Auctioneer')], max_length=20),
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('platform',)},
            },
        ),
        migrations.CreateModel(
            name='PaddleRaise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Bid amount when paddle was raised')),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False, help_text='Auctioneer acknowledged this paddle')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('auction_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paddle_raises', to='auction.auctionsession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.team')),
            ],
            options={
                'ordering': ['-raised_at'],
                'indexes': [models.Index(fields=['player', 'auction_session', '-raised_at'], name='auction_pad_player__486c39_idx'), models.Index(fields=['acknowledged', 'auction_session'], name='auction_pad_acknowl_d93d3b_idx')],
            },
        ),
    ]
